spring.application.name: zuul
server.port: 5555
#zuul.routes.serva.path=/serva/**
#zuul.routes.serva.url=http://localhost:2222/


zuul.routes.serva.path: /**
zuul.routes.serva.serviceId: compute-service

eureka.client.serviceUrl.defaultZone: http://localhost:1111/eureka/
debug: true


security:
  user:
    password: user
  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
  sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /test/login
management:
  security:
    role: HERO

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'

---
spring:
  profiles: default
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:5656/uaa/oauth/token
      userAuthorizationUri: http://localhost:5656/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

---
spring:
  profiles: github
security:
  oauth2:
    client:
      clientId: 89630a412fa314777dc2
      clientSecret: c7a29ec26ec7805e78b496ea67cc13e5a9b8bcf0
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false

    